### ISSUE TITLE
jaeger does not work with pyinstaller

### ISSUE THREAD

**Issue by zgfh** [jaegertracing/jaeger-client-python#165]
after build with pyinstaller, jaeger not work
```
[132] Failed to execute script app_runner
Traceback (most recent call last):
  File "app/app_runner.py", line 39, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "app/storage/database.py", line 39, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "app/storage/db.py", line 6, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "app/metrics/monitor.py", line 11, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "app/metrics/tracing.py", line 13, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/jaeger_client/__init__.py", line 27, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/jaeger_client/config.py", line 25, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/jaeger_client/reporter.py", line 32, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/jaeger_client/thrift_gen/agent/Agent.py", line 12, in <module>
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/jaeger_client/thrift_gen/agent/ttypes.py", line 11, in <module>
ModuleNotFoundError: No module named 'jaeger'
``

**Comment by yurishkuro** [comment]
I don't know what `pyinstaller` is, we install via `pip`

**Comment by zgfh** [comment]
PyInstaller is a program that freezes (packages) Python programs into stand-alone executables. https://www.pyinstaller.org/

**Comment by zgfh** [comment]
i don't know why  `import` in here 
https://github.com/jaegertracing/jaeger-client-python/blob/34364d06e7516384a51551f80478519a51fd13a3/jaeger_client/thrift_gen/agent/ttypes.py#L11 .if readly need, can we change it to `import jaeger_client.thrift_gen.jaeger.ttypes as ttypes`?

**Comment by zgfh** [comment]
thanks,but it not work when use pyinstaller .there is a demo :https://github.com/zgfh/jaegertracing-python-demo

**Comment by yurishkuro** [comment]
One dirty solution could be to add some rewrites to the Makefile to fix the imports in the thrift-generated files, similar to https://github.com/jaegertracing/jaeger-client-go/blob/7476e1f143a58ba020587a2710d36de07ad9ccee/Makefile#L79-L82

**Comment by zgfh** [comment]
@yurishkuro  dirty solution:  https://github.com/jaegertracing/jaeger-client-python/pull/202

**Comment by yurishkuro** [comment]
I am not a fan of #202. The thrift files are generated offline, not on every build, but #202 performs the rewrites during the module installation, which is unnecessary since the generated code is already in the source control and could've been fixed _before putting it there_, i.e. during generation done by the Makefile. We already do a bunch of these rewrites in the Makefile, as I pointed out above.

**Comment by alvaradojl** [comment]
I'm having the same issues with the latest python3.7 and jaeger-client 4.0.0, is there any other solution?

**Comment by JeromeK13** [comment]
Any Updates on that?

**Comment by ethframe** [comment]
Are there any chances that a package with the fix will be released soon?

**Comment by yurishkuro** [comment]
https://pypi.org/project/jaeger-client/4.6.0/
