### ISSUE TITLE
Python version support ?

### ISSUE THREAD

**Issue by rbtcollins** [jaegertracing/jaeger-client-python#177]
Hi, setup.py claims Python 2.7 under classifiers, and I *was* sure that I had the client working on a Python2 codebase. But currently (and this seems to have changed in the last 30 days by my estimate):

```pip install --no-cache-dir jaeger_client requests
Collecting jaeger_client
  Downloading https://files.pythonhosted.org/packages/ee/1d/66cfa8ef438980e523c7ca3ed98c1b865b4e18df4167f32133ae3053c86c/jaeger-client-3.10.0.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 139kB/s
Collecting requests
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 376kB/s
Collecting threadloop<2,>=1 (from jaeger_client)
  Downloading https://files.pythonhosted.org/packages/dc/1a/ecc8f9060b8b00f8a7edac9eb020357575d332a5ad9e32c3372c66a35f79/threadloop-1.0.2-py2-none-any.whl
Collecting thrift (from jaeger_client)
  Downloading https://files.pythonhosted.org/packages/c6/b4/510617906f8e0c5660e7d96fbc5585113f83ad547a3989b80297ac72a74c/thrift-0.11.0.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 1.6MB/s
Collecting tornado<5,>=4.3 (from jaeger_client)
  Downloading https://files.pythonhosted.org/packages/e3/7b/e29ab3d51c8df66922fea216e2bddfcb6430fb29620e5165b16a216e0d3c/tornado-4.5.3.tar.gz (484kB)
    100% |████████████████████████████████| 491kB 2.5MB/s
Collecting opentracing<2,>=1.2.2 (from jaeger_client)
  Downloading https://files.pythonhosted.org/packages/06/c2/90b35a1abdc639a5c6000d8202c70217d60e80f5b328870efb73fda71115/opentracing-1.3.0.tar.gz
Collecting idna<2.7,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.5MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 4.4MB/s
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 3.2MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.4MB/s
Collecting six>=1.7.2 (from thrift->jaeger_client)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting singledispatch (from tornado<5,>=4.3->jaeger_client)
  Downloading https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting backports_abc>=0.4 (from tornado<5,>=4.3->jaeger_client)
  Downloading https://files.pythonhosted.org/packages/7d/56/6f3ac1b816d0cd8994e83d0c4e55bc64567532f7dc543378bd87f81cebc7/backports_abc-0.5-py2.py3-none-any.whl
Installing collected packages: six, singledispatch, certifi, backports-abc, tornado, threadloop, thrift, opentracing, jaeger-client, idna, urllib3, chardet, requests
  Running setup.py install for tornado ... done
  Running setup.py install for thrift ... done
  Running setup.py install for opentracing ... done
  Running setup.py install for jaeger-client ... done
Successfully installed backports-abc-0.5 certifi-2018.4.16 chardet-3.0.4 idna-2.6 jaeger-client-3.10.0 opentracing-1.3.0 requests-2.18.4 singledispatch-3.4.0.3 six-1.11.0 threadloop-1.0.2 thrift-0.11.0 tornado-4.5.3 urllib3-1.22
(jaeger-client-test) robertc@linux-dev:~/work/vmware/symphony-repos/symphony-infra/tracing/test/image$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jaeger_client import config as jaeger_config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robertc/.virtualenvs/jaeger-client-test/local/lib/python2.7/site-packages/jaeger_client/__init__.py", line 27, in <module>
    from .config import Config  # noqa
  File "/home/robertc/.virtualenvs/jaeger-client-test/local/lib/python2.7/site-packages/jaeger_client/config.py", line 24, in <module>
    from .local_agent_net import LocalAgentSender
  File "/home/robertc/.virtualenvs/jaeger-client-test/local/lib/python2.7/site-packages/jaeger_client/local_agent_net.py", line 17, in <module>
    from threadloop import ThreadLoop
  File "/home/robertc/.virtualenvs/jaeger-client-test/local/lib/python2.7/site-packages/threadloop/__init__.py", line 3, in <module>
    from threadloop.threadloop import ThreadLoop  # noqa
  File "/home/robertc/.virtualenvs/jaeger-client-test/local/lib/python2.7/site-packages/threadloop/threadloop.py", line 4, in <module>
    from concurrent.futures import Future
ImportError: No module named concurrent.futures
```

I've done a little looking at this, and jaeger-client-python has depended on threadloop since forever, and that has had a hard dependency on concurrent.futures since 2016 which leaves me a little puzzled as to why I thought it was working.

Anyhow, either we should fix this, and test it in CI, or we should remove Python::2.7 from the setup.py classifiers, as this is clearly not python2.7 compatible as it stands.

**Comment by yurishkuro** [comment]
could it be the matter of which installation tool you're using? As you mentioned, `threadloop` has a hard dependency on `concurrent.futures` and it always included it it:

https://github.com/breerly/threadloop/blob/9d4f83660fd79fe15d741b831be9ee28dccacc30/setup.py#L5-L9

**Comment by yurishkuro** [comment]
PS the dependency on `futures` in Jaeger has been removed in #155, to make it easier to install without requiring the latest setuptools. But Python 2.7 is very much the active target, it's what we use at Uber.

**Comment by rbtcollins** [comment]
No, pip is the standard tool for installing things on Python.

The bug will indeed be the dropping of the dependency in #155 - without that backport specified, you have to have something else somewhere in your dependency tree specifying the inclusion of futures or it won't work on 2.7.

tornado.concurrent doesn't patch sys.modules as far as I can (briefly) tell.

So - it looks to me like tests are passing because of this ```
Collecting futures (from tchannel>=0.27->jaeger-client==3.10.1.dev0)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
```

that is the jaeger-client[tests] depends on tchannel depends on futures.

Any non-test install will be failing at the moment.

I suggest reinstating the futures dependency :).

I think you removed that because of compat concerns with setuptools? Best way to deal with that IMO is to use a pyproject.toml with the setuptools version you need.

https://www.python.org/dev/peps/pep-0518/#specification

```[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>42", "wheel"]  # PEP 508 specifications.
```

But if you can't do that for some reason, we can use the pre-PEP-508 hacky approach that setuptools has supported for many many years of an extra called "" with conditions attached to it. its been a while since I had to fiddle with that (doing PEP-508 was my effort to get *away* from this mess), but its something like:

```
 extras_require={
        'test': [....],
        ':python_version<"3"': [
            'futures'
        ]
    }
```

which while ugly will work back through to insanely old setuptools.

**Comment by yurishkuro** [comment]
Would you like to try a PR, since you're able to reproduce?

I have no knowledge of `pyproject.toml`, so can't say if it would address the compatibility issues we've seen when using conditional dependency on `futures`. The extra_require, if works, seems to be preferable.
